FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY ["Directory.Build.props", "./"]
COPY ["nuget.config", "./"]
COPY ["DotNet.Web/DotNet.Web.csproj", "DotNet.Web/"]
COPY ["DotNet.ServiceDefaults/DotNet.ServiceDefaults.csproj", "DotNet.ServiceDefaults/"]
RUN dotnet restore "DotNet.Web/DotNet.Web.csproj"

COPY ["DotNet.Web/", "DotNet.Web/"]
COPY ["DotNet.ServiceDefaults/", "DotNet.ServiceDefaults/"]

WORKDIR /src/DotNet.Web
RUN dotnet publish "DotNet.Web.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS final
WORKDIR /app
EXPOSE 8080

RUN apt-get update \
    && apt-get install -y --no-install-recommends curl \
    && rm -rf /var/lib/apt/lists/*

ENV ASPNETCORE_URLS=http://+:8080

COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "DotNet.Web.dll"]
